const TracklistActionTypes = {
    FETCH_TRACKLIST_START: 'FETCH_TRACKLIST_START',
    FETCH_TRACKLIST_SUCCESS: 'FETCH_TRACKLIST_SUCCESS',
    FETCH_TIDAL_START: 'FETCH_TIDAL_START',
    FETCH_TIDAL_SUCCESS: 'FETCH_TIDAL_SUCCESS',
    FETCH_TIDAL_FAILURE: 'FETCH_TIDAL_FAILURE',
    START_FETCHING_DISCOGS: 'START_FETCHING_DISCOGS',
    START_FETCHING_SPOTIFY: 'START_FETCHING_SPOTIFY',
    START_FETCHING_WIKIPEDIA: 'START_FETCHING_WIKIPEDIA',
    SUCCESS_FETCHING_DATA: 'SUCCESS_FETCHING_DATA',
    SUCCESS_FETCHING_TIDAL: 'SUCCESS_FETCHING_TIDAL',
    ERROR_FETCHING_DATA: 'ERROR_FETCHING_DATA'
}

export default TracklistActionTypes;