const TracklistActionTypes = {
    START_FETCHING_DISCOGS: 'START_FETCHING_DISCOGS',
    START_FETCHING_SPOTIFY: 'START_FETCHING_SPOTIFY',
    START_FETCHING_WIKIPEDIA: 'START_FETCHING_WIKIPEDIA',
    SUCCESS_FETCHING_DATA: 'SUCCESS_FETCHING_DATA',
    ERROR_FETCHING_DATA: 'ERROR_FETCHING_DATA'
}

export default TracklistActionTypes;